name: Cut Scheduled Release

# on: 
#   schedule:
#     - cron: '0 5 * * 5' # Run the job at 5PM every Friday
on:
  push:
    branches:
      - 'staging'

jobs:
  cut_latest_release_branch:
    name: Cut the latest release
    runs-on: ubuntu-latest

    steps:
    - name: Get Commit Difference Count Between Two Branches
      id: cdc
      uses: jessicalostinspace/commit-difference-action@v1.0.0
      with:
       base-branch: 'staging' 
       secondary-branch: 'master'
